# Generated by Django 5.2.4 on 2026-03-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='needs_onboarding',
            field=models.BooleanField(default=False),
        ),
    ]
