# Generated by Django 5.2.4 on 2026-03-18 21:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('teams', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='team',
                    name='members',
                ),
                migrations.DeleteModel(
                    name='TeamMember',
                ),
                migrations.DeleteModel(
                    name='Team',
                ),
            ],
        ),
    ]
