# Generated by Django 5.2.12 on 2026-04-29 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalNotificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emails_disabled_globally', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Global Notification Setting',
                'verbose_name_plural': 'Global Notification Settings',
            },
        ),
        migrations.CreateModel(
            name='NotificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=64, unique=True)),
                ('is_system_enabled', models.BooleanField(default=True)),
                ('is_email_enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Event Notification Config',
                'verbose_name_plural': 'Event Notification Configs',
            },
        ),
    ]
