# Generated by Django 5.2.12 on 2026-04-29 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_globalnotificationconfig_notificationconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emails_disabled_globally', models.BooleanField(default=False, help_text='If True, this user will never receive any notification emails.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Notification Setting',
                'verbose_name_plural': 'User Notification Settings',
            },
        ),
        migrations.DeleteModel(
            name='GlobalNotificationConfig',
        ),
        migrations.AlterModelOptions(
            name='notificationconfig',
            options={'verbose_name': 'User Event Config', 'verbose_name_plural': 'User Event Configs'},
        ),
        migrations.AddField(
            model_name='notificationconfig',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='event_configs', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notificationconfig',
            name='event_type',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='notificationconfig',
            unique_together={('user', 'event_type')},
        ),
    ]
