# Generated by Django 6.0.4 on 2026-04-08 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0004_alter_team_captain_alter_teaminvitation_invited_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('registration_start', models.DateTimeField(blank=True, null=True)),
                ('registration_end', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('max_teams', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('registration', 'Registration'), ('running', 'Running'), ('finished', 'Finished')], default='draft', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tournaments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tournaments',
            },
        ),
        migrations.CreateModel(
            name='TournamentTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_tournaments', to='teams.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_teams', to='tournaments.tournament')),
            ],
            options={
                'db_table': 'tournament_teams',
            },
        ),
        migrations.AddField(
            model_name='tournament',
            name='teams',
            field=models.ManyToManyField(related_name='tournaments', through='tournaments.TournamentTeam', to='teams.team'),
        ),
        migrations.AddIndex(
            model_name='tournamentteam',
            index=models.Index(fields=['tournament', 'team'], name='tourn_teams_idx_0'),
        ),
        migrations.AddIndex(
            model_name='tournamentteam',
            index=models.Index(fields=['team', 'tournament'], name='tourn_teams_idx_1'),
        ),
        migrations.AlterUniqueTogether(
            name='tournamentteam',
            unique_together={('tournament', 'team')},
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['status'], name='tourn_status_idx'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['registration_start', 'registration_end'], name='tourn_reg_window_idx'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['start_date', 'end_date'], name='tourn_run_window_idx'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['created_by'], name='tourn_creator_idx'),
        ),
        migrations.AddConstraint(
            model_name='tournament',
            constraint=models.CheckConstraint(condition=models.Q(('max_teams__isnull', True), ('max_teams__gt', 0), _connector='OR'), name='tourn_max_teams_pos_or_null'),
        ),
    ]
