# Generated by Django 5.2.12 on 2026-04-19 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0004_alter_team_captain_alter_teaminvitation_invited_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('tech_requirements', models.TextField(blank=True)),
                ('must_have_requirements', models.JSONField(blank=True, default=list)),
                ('max_teams', models.PositiveIntegerField(blank=True, null=True)),
                ('min_team_members', models.PositiveIntegerField(blank=True, null=True)),
                ('rounds_count', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('registration', 'Registration'), ('running', 'Running'), ('finished', 'Finished')], default='draft', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tournaments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('tech_requirements', models.TextField(blank=True)),
                ('must_have_requirements', models.JSONField(blank=True, default=list)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('passing_count', models.PositiveIntegerField(blank=True, null=True)),
                ('winners_count', models.PositiveIntegerField(blank=True, null=True)),
                ('evaluation_criteria', models.CharField(choices=[('score', 'Score')], default='score', max_length=32)),
                ('materials', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('submission_closed', 'SubmissionClosed'), ('evaluated', 'Evaluated')], default='draft', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='tournaments.tournament')),
            ],
            options={
                'ordering': ('tournament_id', 'position'),
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_url', models.URLField()),
                ('demo_video_url', models.URLField(blank=True)),
                ('demo_video_file', models.FileField(blank=True, upload_to='tournaments/demo_videos/')),
                ('live_demo_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_submissions', to=settings.AUTH_USER_MODEL)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='tournaments.round')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='teams.team')),
            ],
            options={
                'ordering': ('-updated_at',),
                'constraints': [models.UniqueConstraint(fields=('team', 'round'), name='uniq_submission_team_round')],
            },
        ),
        migrations.AddConstraint(
            model_name='round',
            constraint=models.UniqueConstraint(fields=('tournament', 'position'), name='uniq_round_tournament_position'),
        ),
        migrations.AddConstraint(
            model_name='round',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('tournament',), name='uniq_active_round_per_tournament'),
        ),
    ]
