# Generated by Django 6.0.4 on 2026-04-10 01:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_alter_team_captain_alter_teaminvitation_invited_by'),
        ('tournaments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='min_teams',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='tournament',
            name='rounds_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='tournament',
            constraint=models.CheckConstraint(condition=models.Q(('min_teams__gte', 2)), name='tourn_min_teams_floor'),
        ),
        migrations.AddConstraint(
            model_name='tournament',
            constraint=models.CheckConstraint(condition=models.Q(('rounds_count__gte', 1)), name='tourn_rounds_count_pos'),
        ),
    ]
