# Generated by Django 5.2.12 on 2026-04-23 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_juryassignment_submissionevaluation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissionevaluation',
            name='assignment',
        ),
        migrations.DeleteModel(
            name='JuryAssignment',
        ),
        migrations.DeleteModel(
            name='SubmissionEvaluation',
        ),
    ]
