# Generated by Django 5.2.4 on 2026-04-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_remove_submissionevaluation_assignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='criteria',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
