# Generated by Django 5.2.4 on 2026-04-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_tournament_criteria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='must_have_requirements',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='tech_requirements',
        ),
        migrations.AlterField(
            model_name='round',
            name='must_have_requirements',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='round',
            name='tech_requirements',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
