# Generated by Django 5.2.4 on 2026-04-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_remove_tournament_must_have_requirements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='description',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
