# Generated by Django 5.2.4 on 2026-04-26 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_alter_round_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='rounds_count',
        ),
    ]
