# Generated by Django 5.2.4 on 2026-04-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_remove_tournament_rounds_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='criteria',
        ),
        migrations.AddField(
            model_name='round',
            name='criteria',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
