# Generated by Django 5.2.4 on 2026-04-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0009_remove_tournament_criteria_round_criteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentteamregistration',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
