# Generated by Django 5.2.4 on 2026-04-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0010_tournamentteamregistration_is_active'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='round',
            name='uniq_round_tournament_position',
        ),
        migrations.RemoveField(
            model_name='round',
            name='position',
        ),
        migrations.AddConstraint(
            model_name='round',
            constraint=models.UniqueConstraint(fields=['tournament', 'start_date'], name='uniq_round_tournament_start_date'),
        ),
    ]