# Generated by Django 6.0.4 on 2026-04-30 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0011_remove_round_position_add_start_date_constraint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='round',
            options={'ordering': ('tournament_id', 'start_date')},
        ),
        migrations.RemoveField(
            model_name='round',
            name='winners_count',
        ),
    ]
