# Generated by Django 5.2.4 on 2026-05-04 18:30

from django.db import migrations


DEFAULT_ICONS = [
    {'name': 'meet_default', 'path': 'icons/camera.svg'},
    {'name': 'event_default', 'path': 'icons/calendar.svg'},
]


def seed_default_icons(apps, schema_editor):
    Icon = apps.get_model('tournaments', 'Icon')
    for icon_data in DEFAULT_ICONS:
        Icon.objects.get_or_create(name=icon_data['name'], defaults={'path': icon_data['path']})


def remove_default_icons(apps, schema_editor):
    Icon = apps.get_model('tournaments', 'Icon')
    Icon.objects.filter(name__in=[i['name'] for i in DEFAULT_ICONS]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0013_icon_event'),
    ]

    operations = [
        migrations.RunPython(seed_default_icons, remove_default_icons),
    ]
