# Generated by Django 5.2.4 on 2026-03-18 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='Team',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=255)),
                        ('email', models.EmailField(max_length=254)),
                        ('organization', models.CharField(blank=True, max_length=255)),
                        ('contact', models.CharField(blank=True, max_length=100)),
                        (
                            'captain',
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.PROTECT,
                                related_name='captained_teams',
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        'db_table': 'accounts_team',
                    },
                ),
                migrations.CreateModel(
                    name='TeamMember',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        (
                            'team',
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name='team_members',
                                to='teams.team',
                            ),
                        ),
                        (
                            'user',
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name='team_memberships',
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        'db_table': 'accounts_teammember',
                        'indexes': [models.Index(fields=['user', 'team'], name='team_members_index_0')],
                        'unique_together': {('user', 'team')},
                    },
                ),
                migrations.AddField(
                    model_name='team',
                    name='members',
                    field=models.ManyToManyField(
                        related_name='teams',
                        through='teams.TeamMember',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
