# Generated by Django 5.2.12 on 2026-04-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
