# Generated by Django 5.2.12 on 2026-04-26 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_certificate_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='pdf_file',
        ),
    ]
