# Generated by Django 5.2.12 on 2026-04-26 19:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_remove_certificate_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='unique_code',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True),
        ),
    ]
